config/routes.rb
Rails.application.routes.draw do
  
  get 'discover' => 'static_pages#discover'
  
  

  devise_for :users,  :controllers => { registrations: 'registrations',  omniauth_callbacks: 'omniauth_callbacks' }  
  

 
   root 'static_pages#welcome'
    
      get 'home' => 'users#home'
      get 'promote' => 'users#promote'
      get 'users' => 'users#index'
      
     
     
    
    get  ':id' => 'users#show'  , as: 'user'
      resources :profiles, only: [ :update, :edit, :show ]
     
        scope'/(:user_id)' do
       
         resources :ventures  do
             resources :posts,  only: [ :create , :destroy]
         end 
        end 
    
   
     
end
     
     
   
   
     
    
   
     
     

app/models/venture.rb
class Venture < ActiveRecord::Base
  belongs_to :profile
  has_many :posts , dependent: :destroy
  
 
  
  has_attached_file :image, styles: { small: "64x64#", med: "100x100#", large: "300x300#"  },
  :default_url => "/assets/paper.png"
    
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
     
  validates :title, presence: true ,length: { maximum: 50 , minimum: 3}
  validates :goal,  presence: true , length: {maximum: 250 , minimum: 10} 
  validates :profile_id, presence: true   
end

app/controllers/ventures_controller.rb
class VenturesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy ]

   
   def index
        @user = current_user
   end 
   
   def show
       @user =   User.friendly.find(params[:user_id])
       @venture = Venture.find(params[:id])
       @post = Post.new
       @posts = @venture.posts
      
   end 
   
   def edit
       @venture = Venture.find(params[:id])
   end 
    
   def create
        #  @user =   User.friendly.find(params[:id])
        #  @get_fame = @user.get_fame
        @profile = current_user.profile
        @venture = @profile.ventures.build(venture_params)
        if @venture.save!
         flash[:success] = "created!"
         redirect_to @current_user
        else 
          redirect_to @current_user
          flash[:danger] = "somthing went wrong try again"
        end 
            
   end 
   
   def destroy
       @venture =  Venture.find(params[:id])
       @venture.destroy
       flash[:success] = "byte deleted"
       redirect_to current_user
   end  
   
    private

    def venture_params
      params.require(:venture).permit( :goal , :image , :tags , :title )
    end
    
end

app/helpers/ventures_helper.rb
module VenturesHelper
end

app/views/ventures/_form.html.erb
  <div class="form-group" >
  <%= form_for(@venture)  do |f| %>
        <%= f.text_area :title , :class => 'form-control' , :placeholder=>"title" %>
        <%= f.text_area :goal , :class => 'form-control' , :placeholder=>"goal" %>
        <%= f.text_area :tags , :class => 'form-control' , :placeholder=>"tags" %>
        <%= f.file_field :image  , :class => 'form-control imagefile' %>
        <button  type=button class="btn btn-defaul  btn-block image_button" ><span class="glyphicon glyphicon-camera"></span></button><br>  
       
         <div class="caption thumbnail"  style="position:relative">
             
       <a class="glyphicon glyphicon-remove image-cancel" ></a> <br>
       <%= link_to image_tag @venture.image.url(:large), class:"some-image" ,  size: "200x200"  %>
        </div>
        <%= f.submit "save", :class => 'btn btn-primary btn-md btn-block' %>
       
  <% end %>
 </div> 
 

app/views/ventures/_index.html.erb
<br> 
<div class="thumbnail polaroid"> 
 <div class=" img-thumbnail" style=" position:relative; width:80px; height:80px ; overflow:hidden ">
    <%= render "ventures/new" %><br>
  </div> 
  
<% @user.profile.ventures.each do |venture| %>
 
   <div class=" img-thumbnail " style="position:relative; width:80px; height:80px ; overflow:hidden ">
       <%= link_to image_tag(venture.image.url(:med)) , venture_path(@user,venture) %>
       <h3 class="image_text"><%= venture.title %></h3> 
   </div> 
       
   <!--<span class="glyphicon glyphicon-pencil"></span>  -->
 
<% end %>
<a> <h3> click here to see more</h3></a>
</div>


<style> 

.image_text { 
   position: absolute; 
   top: -20px; 
   left: 20px; 
   width: 100%; 
   color: white;
   font-size:16px;
   /*overflow:hidden*/
}

</style>

app/views/ventures/_new.html.erb
<style>
  #createbytebutton{
  width: 75px !important;
  height: 75px !important;
}

</style>
 
  <button type="button" id="createbytebutton" class="btn btn-primary"  data-toggle="modal" data-target="#myModal">Create <br> Byte</button>

  <!-- Modal -->
 <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
    
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <%= render 'ventures/form' %>
                     
            </div>
       
      </div>
      
    </div>
  </div>

app/views/ventures/edit.html.erb
 <div class="col-md-6 col-md-offset-3">
     
    <%= render 'form'%>
   
      <button type="button" class="btn btn-primary btn-lg btn-block">
             <%= link_to " Delete" , venture_path(@user ,@venture)  , method: :delete %> </button>  
  </div> 

app/views/ventures/show.html.erb
<head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
 
<div class="row">
     
    <div class="col-md-4">
         <div class="thumbnail">
            <%= link_to image_tag(@venture.image.url(:large))  %>
                <div class="caption">
                    <h1><%= @venture.title %></h1> 
                    <%= @venture.goal %>  <br>
                    <%= @venture.tags %> <br>
                    <%= link_to 'manage' , edit_venture_path(@venture) %><br>
                    <%= link_to 'chat' %> <br> 
                    <%= link_to 'public' %> <br> 
                    <%= link_to 'dashboard' %> <br> 
                    <%= link_to 'action' %> 
                </div>
        </div> 
        
    
        
    </div>

    <div class="col-md-6">
       <!--<button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#myModal">Create Byte</button>-->
       
        <%= render "posts/form" %>
        <%= render "posts/index" %>      
    </div> 
  
</div> 