config/routes.rb
Rails.application.routes.draw do
  
  get 'discover' => 'static_pages#discover'
  
  

  devise_for :users,  :controllers => { registrations: 'registrations',  omniauth_callbacks: 'omniauth_callbacks' }  
  

 
   root 'static_pages#welcome'
    
      get 'home' => 'users#home'
      get 'promote' => 'users#promote'
      get 'users' => 'users#index'
      
     
     
    
    get  ':id' => 'users#show'  , as: 'user'
      resources :profiles, only: [ :update, :edit, :show ]
     
        scope'/(:user_id)' do
       
         resources :ventures  do
             resources :posts,  only: [ :create , :destroy]
         end 
        end 
    
   
     
end
     
     
   
   
     
    
   
     
     

app/models/user.rb
class User < ActiveRecord::Base
    
  has_one :profile ,dependent: :destroy
  after_create :setup_profile
  has_many :identities
  attr_accessor :current_password
  
  extend FriendlyId
  friendly_id :username, use: :slugged
  
 
  
  has_attached_file :image, styles: { med: "100x100#", large: "200x200#" , background: "1100x500!" },
  :default_url => "/assets/profile-pic.png"
    
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable , :omniauth_providers => [:facebook , :twitter]
         
  validates :name, presence: true ,length: { maximum: 50 , minimum: 3}
  validates :gender  , presence: true 
  
        
    # scope :location, -> (location_id) { where location_id: location_id }
    scope :gender, -> (gender) { where gender: gender }
    # scope :dob, -> (dob) { where dob: dob } 
    # scope :name, -> (name) { where name: name } 

  def setup_profile
    if self.profile.nil?
     self.create_profile # or Profile.create(user_id: self.id)
    end 
  end
  
  
  def self.from_facebook(auth)
      user = User.new
      user.email =  "alfred@gmail.com"
      user.password = "alfred1992"
      user.password_confirmation = "alfred1992"
      user.username = "alfred" 
      user.name = auth.info.name 
      user.image =URI.parse(auth.info.image)
      user.image_file_name= auth.info.name + ".jpg"
      # user.dob = Date.strptime(auth.extra.raw_info.birthday, '%m/%d/%Y')
      user.gender = auth.extra.raw_info.gender 
      user.save!
      user.image.reprocess!
     
      user
  end 
  
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  
    def show
      @user =   User.friendly.find(params[:id])
      @venture = Venture.new
      @posts = @user.profile.posts
    
    end 
    
    def update 
        
    end 
    
    def index 
       @users = User.where(nil) 
       
       @users = @users.gender(params[:gender]) if params[:gender].present?
       
       
       respond_to do |format|
        format.html
        format.json
        format.js   {}
      end
      # @users = @users.gender('male')
      # raise @users.inspect
      # @users = @users.name(params[:name]) if params[:name].present?
      # @users = @users.dob(params[:dob]) if params[:dob].present?
       
      # redirect_to users_path
       
    end 
    
    def home
       
    end 
    
    def promote
      # current_user.find_for_oauth(env["omniauth.auth"])
      # @identity = Identity.find_by(user_id:current_user.id)
      @identity = current_user.identities.where(provider:"twitter").first
      # raise @identity.inspect 
      client = Twitter::REST::Client.new do |config|
        config.consumer_key        = 'eZG402S9yDURoXrHWwJf6K56Y' 
        config.consumer_secret     = 	'UDBB0yvHILfcMSgMXOnbGSdbOFwQbq47qYTlM9FY7vgXMKaYmM'
        config.access_token        =  @identity.oauth_token
        config.access_token_secret =  @identity.oauth_secret
      end
      # client.current_user("testoauthsocial")
      # # client.user("gem")
      # client.followers("gem")
      @twitter_user = client.user('gem')
      client.update("I'm tweeting with @gem!")
    end
   
   private 
#   def user_params
#       params.require(:user).permit( :name , :image , :dob )
#   end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<%=  @users.each do |user| %>
 
 <div class="col-sm-4 ">
    
      
                <div class="row thumbnail polaroid" style="margin: auto; " >
                    
                    <div class ="col-xs-7 col-md-5 well" > 
                            <%= link_to image_tag user.image.url(:large) %>
                            <%= user.profile.id %>
                    </div>
                      
                    <div class ="col-xs-7 col-md-5 " >
                        
                    <h5 class="user"> <%= link_to user.name, user %></h5>
                        <p > <%= user.profile.bio  %></p> 
                        <p > <%= user.gender  %></p> 
                    </div> 
                     
                   
                </div>
 </div>

<% end %> 





                     

app/views/users/index.html.erb
<%=  @users.each do |user| %>
      
 <div class="col-sm-4 ">
    
      
            <section class="user_info">
                <div class="row thumbnail polaroid" style="margin: auto; " >
                    
                    <div class ="col-xs-6 col-md-5 well" > 
            
                        <div >
                            <%= link_to image_tag user.image.url(:large) %>
                            <%= user.profile.id %>
                            <p> followers  </p>
                            <p> following </p>
                          
                         </div>
                    </div>
                      
                    <div class ="col-xs-6 col-md-5 " >
                        
                    <h3 class="user"> <%= link_to user.name, user %></h3>
                        <p > <%= user.profile.bio  %></p> 
                           <p > <%= user.gender  %></p> 
                    </div> 
                     
                   
                </div>
 </div>

<br>
<% end %> 





                     

app/views/users/index.js.erb
$('#users').html("<%= j (render 'users/index') %>");

app/views/users/promote.html.erb
<%= @twitter_user.followers_count %>

app/views/users/show.html.erb
 <!--style="background-color:#6534ff"-->



<!--<row >-->
    <div class="col-sm-3 ">
    
      
            <section class="user_info">
                <div class="row thumbnail polaroid" style="margin: auto; " >
                    
                    <div class ="col-xs-6 col-md-5 well" > 
                      <%= link_to "click to tweet" , promote_path(@user) %> 
                        <%= link_to "Change Pic " , edit_user_registration_path( @user) ,  style:"position:absolute " %> 
                        <div >
                               
                            
                            <%= link_to image_tag @user.image.url(:large) %>
                            <%= @user.profile.id %>
                            <p> followers  </p>
                            <p> following </p>
                          
                         </div>
                    </div>
                      
                    <div class ="col-xs-6 col-md-5 " >
                        
                    <h5 class="user"> <%= link_to @user.name, @user %></h5>
                      
                        <h4> Bio   <%= link_to "Edit " , edit_user_registration_path( @user) + "#general" ,  style:"font-size:15px; ", class:"glyphicon glyphicon-pencil" %> </h4>
                        <p > <%= @user.profile.bio  %></p> 
                          
                    </div> 
                     
                   
                </div>
            </section>

           
           
           
            <%= render "ventures/index" %> 
    </div>
  
    <div class="col-md-6 " >
        
       <h2 style="color:#cc0052;"> recent updates</h2>
        <%= render "posts/index" %>      
        
    </div>
    
    <div class="col-sm-3 " >
        <form class="navbar-form navbar-right" >
               <input size="30" type="text" class="form-control" placeholder="go for it">
                <%= link_to "  #complaint " %>
                <%= link_to "  #idea  " %>
                <%= link_to "  #proudct" %>
                <%= link_to "  #content" %>
               <button class="btn btn-primary btn-md btn-block"> post </button>
              
        </form>
        <br> 
        <h4 style="color:#337ab7;">   OUT OF IDEAS ? .. </h4>
        <p>  give them the ability to fillter these coming posts via 
          age  , gender , profession,  and catorory like content . idea?
          as well as support from the masses.
        </p>
        <br>
         <br>
         <h5 style="color:#337ab7;">   some content suggiestions .. </h5>
        <br>
         <br>
         <h5 style="color:#337ab7;">   ideas .. </h5>
    </div>

    
<!--</row>-->