config/routes.rb
Rails.application.routes.draw do
  
  get 'discover' => 'static_pages#discover'
  
  

  devise_for :users,  :controllers => { registrations: 'registrations',  omniauth_callbacks: 'omniauth_callbacks' }  
  

 
   root 'static_pages#welcome'
    
      get 'home' => 'users#home'
      get 'promote' => 'users#promote'
      get 'users' => 'users#index'
      
     
     
    
    get  ':id' => 'users#show'  , as: 'user'
      resources :profiles, only: [ :update, :edit, :show ]
     
        scope'/(:user_id)' do
       
         resources :ventures  do
             resources :posts,  only: [ :create , :destroy]
         end 
        end 
    
   
     
end
     
     
   
   
     
    
   
     
     

app/models/post.rb
class Post < ActiveRecord::Base
   

  belongs_to :venture
  belongs_to :profile
  
 default_scope -> { order(created_at: :desc) }
  
 has_attached_file :image, styles: {  med: "100x100#", large: "300x300#" , xlarge: "550x550#" },
 :default_url => "/assets/profile-pic.png"

 validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
 validates :venture_id, presence: true 
 
 def get_fame_id_for_post
   self.get_fame_id = current_user.get_fame.id 
   self.save
 end 
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy ]
    
  def create
   
    @venture = Venture.find(params[:venture_id])
    @post = @venture.posts.build(post_params)
    # @venture.profile.posts.build(post_params)
    @profile = current_user.profile
    @post.profile_id = @profile.id
    # @profile = current_user.profile
    @post.save
    redirect_to venture_path(current_user, @venture)
  end
  
 

  def show
  end


  def edit
  end
  
  def destroy 
    @venture = Venture.find(params[:venture_id])
    @post = Post.find(params[:id])
    if @post.destroy
       flash[:success] = "deleted!"
       redirect_to venture_path(current_user, @venture)
    end    
  
  end 
  
  private
  
  def post_params
    params.require(:post).permit(:text, :image )  
  end 
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
 
<div class="form-group" >

    <%= form_for [@venture, @post]  do |f|  %>
       
        <%= f.text_area :text , class:"form-control" , placeholder:"text" %>
         <button  type=button class="btn btn-defaul  btn-block image_button" ><span class="glyphicon glyphicon-camera"></span></button> 
      
        <%= f.file_field :image  , class:'form-control imagefile'  %><br>
        <%= f.submit  "save",  class:'btn btn-primary btn-md btn-block' %>
      
    <% end %>
     <button  type=button class="btn btn-default image-cancel" ><span class="glyphicon glyphicon-remove"></span></button>   
    <img class="some-image"  />
      
</div>



<script> 
           
   //  $('#new_post').fileupload({
   //    // dataType: 'json',
      
   //     add: function (e, data) {
   //        $( "#save_post" ).unbind();
   //       //  data.context = $('<button/>').text('Upload').appendTo(document.body);
   //        if (data.files && data.files[0]) {
   //           var reader = new FileReader();
   //           reader.onload = function(e) {
   //                $('#some-image').attr('src', e.target.result);
   //           };
             
   //           reader.readAsDataURL(data.files[0]);
            // $('#post-image-cancel').css('display','inline');
            
             
            //  $('#post-image-cancel').click(function () {
            //     $('#some-image').attr('src', "");
            //    $('#post-image-cancel').css('display','none')
            //  });
               
            //  $("#new_post").submit(function(){
            //           return false;
            //          //  evt.preventDefault();
                       
            //     });
             
            //  $("#save_post").click(function(e){
             
              
            //     data.submit();
               
       
            //  });
      //     }
      // },
      
      //  done: function (e, data) {
      //       data.context.text('Upload finished.');
      //  }
   //  });
    
    
// });
  

</script>

app/views/posts/_index.html.erb
<% @posts.each  do |post| %>

<div class="thumbnail polaroid" style="margin-bottom:-4px;">
      
    <span style="float:left;">
        <%= link_to image_tag(post.venture.image.url(:small) ,:style=>'border-radius: 5px') %>
     
    </span> 
     <h3  class="user"><%= link_to post.venture.title, venture_path(@user, post.venture) %></h3>
    <%=  post.text %>
    <%= link_to image_tag(post.image.url(:xlarge) ) %><br>
    <%=  post.tags %>
   
    <span class="timestamp">
     <p style="color:#337AB7;"> Posted <%= time_ago_in_words(post.created_at) %> ago. </p>
    </span><br>
    
    <%= link_to "              |" , venture_post_path( post.venture ,post) ,  style:"font-size:21px; color:#cc0052;", class:"glyphicon glyphicon-remove" , method: :delete %> 
    <a herf="" class="glyphicon glyphicon-retweet " style="font-size:21px;color:grey;">  | </a>
    <!--<a herf="" class=" glyphicon glyphicon-usd" style="font-size:21px;color:grey;">   |</a>-->
    <a herf="" class=" glyphicon glyphicon-heart" style="font-size:21px; color:#cc0052;">   |</a>
    <!--<a herf="" class="glyphicon glyphicon-retweet " style="font-size:25px; color:grey;">   </a>-->
    <!--<a herf="" class=" glyphicon glyphicon-usd" style="font-size:13px; right:25px; top:-4px; color:#cc0052; ">   </a>-->
   
   
   
     <button type="button"  class="btn btn-primary"  data-toggle="modal" data-target="#request">request</button>
     <div class="modal fade" id="request" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
                <div class="modal-body">
                    <%= form_tag  users_path, method: 'get' , id: 'users_search',   remote: true do %>
                     
                     <%= label_tag 'gender' %>
                    
                   
                        <select name="gender" >
                          <option value="">both</option>
                          <option value="male">male</option>
                          <option value="female">female</option>
                        </select>
                        
                      <%= label_tag 'channels' %>
                         <select name="channels" >
                          <option value="all">all</option>
                          <option value="facebook">facebook</option>
                          <option value="twitter">twitter</option>
                          <option value="instagram">instagram</option>
                          <option value="linkden">linkden</option>
                      </select>
                        
                      <%= label_tag 'type' %>
                         <select name="type" >
                          <option value="poll">poll</option>
                          <option value="promote">promote</option>
                          <option value="showdown">verses</option>
                          <option value="advice">advice</option>
                        </select>
                        
                     <%= label_tag 'age' %>
                      <%= number_field_tag 'age', '12', max: 80 , min: 8 %> to <%= number_field_tag 'age', '75', max: 80 , min: 8 %>
                      
                    <%= label_tag 'requests' %>
                      <%= number_field_tag 'age', '1', max: 1000 , min: 1 %> 
                      
                    <%= label_tag 'likes' %>
                      <%= text_field_tag 'age', '1', max: 1000 , min: 1 %> 
                      
                   <%= label_tag 'occupation' %>
                      <%= text_field_tag 'age', '1', max: 1000 , min: 1 %> 
                      
                      
                    <%= submit_tag 'search' , class:'btn btn-primary btn-md btn-block' %>
                    
                    
                    <div id="users"> 
                    

                                       
                    </div>
                    <% end %> 
                    
                    
                   
                   
                </div>
          </div>
        </div>
      </div>
   
</div>

<% end %>

app/views/posts/index.js.erb
$('#users').html( <p> alfre daw d asdf ad f </p>");