config/routes.rb
Rails.application.routes.draw do
  
  get 'discover' => 'static_pages#discover'
  
  

  devise_for :users,  :controllers => { registrations: 'registrations',  omniauth_callbacks: 'omniauth_callbacks' }  
  

 
   root 'static_pages#welcome'
    
      get 'home' => 'users#home'
      get 'promote' => 'users#promote'
      get 'users' => 'users#index'
      
     
     
    
    get  ':id' => 'users#show'  , as: 'user'
      resources :profiles, only: [ :update, :edit, :show ]
     
        scope'/(:user_id)' do
       
         resources :ventures  do
             resources :posts,  only: [ :create , :destroy]
         end 
        end 
    
   
     
end
     
     
   
   
     
    
   
     
     

app/views/layouts/_header.html.erb
   
      
      
 <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

      
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="font-size:40px;color:white;" href="#">famenova</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
        
          <ul class="nav navbar-nav navbar-left">
           <li>   <%= link_to 'Discover', discover_path , class:"glyphicon glyphicon-globe "    %></li>
          </ul>
           
          <ul class="nav navbar-nav navbar-right">
             
          
             
          <% if user_signed_in? %>
          
             <ul class="nav navbar-nav" >
                <li>   <%= link_to 'Requests',   home_path  , class:"glyphicon glyphicon-flag"  %></li>
            </ul> 
        
             <ul class="nav navbar-nav" style="padding-right:110px">
        
     
          
                <li>   <%= link_to 'Home',   home_path  , class:"glyphicon glyphicon-home "  %></li>
                <li>   <%= link_to current_user.name,   user_path(current_user)    %></li>
                
          
            </ul> 
        
       
      
            <ul class="  nav navbar-nav navbar-right"   style="padding-right:10px">
                <li class="dropdown ">
                  <a class="dropdown-toggle " data-toggle="dropdown" href="#">
                     <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                     <span class="caret"> </span>
                  </a>
                  <ul class="dropdown-menu  " role="menu">
                      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
            </ul>
             
            <form class="navbar-form navbar-right" >
               <input size="50" type="text" class="form-control" placeholder="Search...">
            </form>
        
        
        
        <% else %>
        
        
            
        
             <%= render "devise/sessions/new" %>
         
        <% end %>
            
            
            
          </ul>
        
        </div>
      </div>
    </nav>
    
<script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
 


<script>
$('.dropdown-toggle').dropdown()  ;

</script>

app/views/layouts/_headerr.html.erb
   
      
      
 <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

      
<nav class="navbar  navbar-fixed-top" style="background-color:white;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="font-size:40px;color:#337ab7;" href="#">synrge </a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
        
         
           <% if  '\/discover\/'.match(request.path)   %>
              
               <ul class="nav navbar-nav navbar-left">
            <form class="navbar-form navbar-right" >
               <input size="50" type="text" class="form-control" placeholder="Search...">
            </form>
              </ul>
        
           <% end %> 
         
            
           <div class="col-md-6 navbar-right " >
                <ul class="nav nav-pills" style="position:fixed ;" >
              <li role="presentation"> <%= link_to 'Discover', discover_path , class:"glyphicon glyphicon-globe "    %></li>
          
             
          <% if user_signed_in? %>
          
           
         
          
              <li role="presentation" class="active"><%= link_to 'Home',   home_path  , class:"glyphicon glyphicon-home "  %></a></li>
              <li role="presentation"><a href="#account">Inbox</a></li>
             <li role="presentation"><a href="#general"> Dashboard</a></li>
              <li role="presentation"><%= link_to current_user.name,   user_path(current_user) %></li>
            </ul>
           
       
      
            <ul class="  nav navbar-nav navbar-right "   style="padding-right:10px">
                <li class="dropdown ">
                  <a class="dropdown-toggle " data-toggle="dropdown" href="#">
                     <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                     <span class="caret"> </span>
                  </a>
                  <ul class="dropdown-menu  " role="menu">
                      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
            </ul>
             
           
        
        
        <% else %>
        
             <form class="navbar-form navbar-right" >
               <input size="50" type="text" class="form-control" placeholder="Search...">
            </form>
        
            
        
             <%= render "devise/sessions/new" %>
         
        <% end %>
            
            
            
        
        </div>
      </div>
    </nav>
    
<script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
 


<script>
$('.dropdown-toggle').dropdown()  ;

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>shoutout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="background-color:rgb(242, 242, 242); margin-left:-20px;
 margin-right:-20px;" >



<div class="container ">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  
</div>

  

<%= render "layouts/headerr" %>


<div class="container">
 
  <%= yield %>
</div>

</body>

<br> 
 <% debug(params) if Rails.env.development? %>
</html>